name: DevSecOps Secure SDLC Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
       # Exercise 37: Semgrep SAST Scan (Excluding node_modules for speed)
       - name: Run Semgrep SAST
        run: |
          python3 -m pip install semgrep
          python3 -m semgrep --config=auto --exclude node_modules --error

      # Exercise 38: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t 192.168.56.50:5000/juice-shop:latest 
      # Exercise 38: Trivy Container Scan
      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '192.168.56.50:5000/juice-shop:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'

      # Exercise 39: Push to Registry Gate
      - name: Push to Local Registry
        if: success()
        run: |
          echo "Security scan gates passed cleanly."
